### ISSUE TITLE
returned objects bugs and inconsistency

### ISSUE THREAD

**Issue by ArbelNathan** [IBM/pyds8k#28]
get_volume - flashcopy attribute is all storage flashcopies and not only the volume's.

\>>> volume = client.get_volume('0000')
\>>> volume.flashcopy
[<FlashCopy: 1310:1311>, <FlashCopy: 503A:503C>, <FlashCopy: 5130:51D1>, <FlashCopy: 51AA:51EB>, <FlashCopy: 51D1:51D6>, <FlashCopy: 55A9:55AA>]

flashcopy - 2 different objects flashcopy/flashcopies which dont have all the data and missing out_of_sync_tracks/backroundcopy respectively.
flashcopy is the object that returns from get_flashcopies_by_volume and flashcopies from get_cs_flashcopies

\>>> flashcopies_by_volume = client.get_flashcopies_by_volume("503A")
\>>> flashcopies_by_volume
[<FlashCopy: 503A:503C>]
\>>> type(flashcopies_by_volume[0])
<class 'pyds8k.resources.ds8k.v1.flashcopy.FlashCopy'> -> `flashcopy`
\>>> flashcopies_by_volume[0].backgroundcopy
'disabled'

\>>> cs_flashcopies = client.get_cs_flashcopies("503A:503C")
\>>> cs_flashcopies
<FlashCopy: 503A:503C>
\>>> type(cs_flashcopies)
<class 'pyds8k.resources.ds8k.v1.cs.flashcopies.FlashCopy'> -> `flashcopies`
\>>> cs_flashcopies.backgroundcopy
Traceback (most recent call last):
  File "/usr/lib64/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/opt/app-root/lib64/python3.8/site-packages/pyds8k/resources/ds8k/v1/common/base.py", line 97, in __getattr__
    return super(Base, self).__getattr__(key)
  File "/opt/app-root/lib64/python3.8/site-packages/pyds8k/base.py", line 393, in __getattr__
    raise AttributeError(k)
AttributeError: backgroundcopy

**Comment by AnboAnbo** [comment]
per most recent REST doc - https://www.ibm.com/docs/en/ds8900/9.0.2?topic=api-queries
![image](https://user-images.githubusercontent.com/12315744/187527032-bbe26221-441c-4b05-92c7-0316e54dd91e.png)

v1/flashcopy is deprecated hence v1/cs/flashcopies should be used for R8+ where backgroundcopy is not among the valid fields.

please let me know if you have further questions.

thx

**Comment by ArbelNathan** [comment]
what about the `get_volume` part?

get_volume - flashcopy attribute is all storage flashcopies and not only the volume's.

>>> volume = client.get_volume('0000')
>>> volume.flashcopy
[<FlashCopy: 1310:1311>, <FlashCopy: 503A:503C>, <FlashCopy: 5130:51D1>, <FlashCopy: 51AA:51EB>, <FlashCopy: 51D1:51D6>, <FlashCopy: 55A9:55AA>]

**Comment by AnboAnbo** [comment]
your findings are correct, I will get it fixed soon, @ArbelNathan

**Comment by AnboAnbo** [comment]
fix is in 76b4390
@ArbelNathan 
please let me know whether it solves the problem you raised.

thanks

**Comment by ArbelNathan** [comment]
@AnboAnbo this is not fixing the `get_volume` bug

**Comment by AnboAnbo** [comment]
I have tested function calls like 
```
    the_vol = c.get_volume('0000')
    copies = the_vol.flashcopy
```
and the copies returned by flashcopy are all relevant to volume 0000
wonder whether you could provide more details about not fixing get_volume bug.

Thanks!

**Comment by ArbelNathan** [comment]
what details can I add?

**Comment by ArbelNathan** [comment]
@AnboAnbo after retesting it is indeed fixed the problem
